### ISSUE TITLE
BUG: update documentation to avoid PiP frame drops in inactive browser tabs

### ISSUE THREAD

**Issue by jochmann** [pxi-gmbh/pipfy#1]
encountered both in Firefox and Chrome on Mac/PC

may be only happening while in **flipped** mode.

- testing regular PiP in Firefox on Win for ~5mins: no issue
- flipping the image while in PiP in Firefox on Win after running it for >5mins: image is frozen (new frame every 30secs)
- the framerate recovers while switching focus of OS-windows back to the browser tab where the video is originating.
- UPDATE: looks like this happens in Firefox on Windows, when the video is running in an *inactive tab*. Pulling the tab into a browser window of its own gives me a smooth framerate, even when another browser window or app window is in focus.

**Comment by gaenseklein** [comment]
I encouter a frame-drop on flipped PiP whenever the origin-page is in an inactive tab. same on firefox and chromium. 
"unflipped" PiP does not have the same problem (it comes directly from webcam, not from canvas). 
The origin seems to be how Canvas in inactive tabs are handled by the browser - as it does not know that we are still using the canvas "live" it slows down processes on the origin-tab, which then generates not enough frames per second for the video to be still in 25fps. 

this seems harder to fix, maybe trying with webworker? 
easiest fix for users would be to open origin-page in own window, so its always in an active tab. so a good explanation seems easier then fixing this issue. forced opening into new window does not work on most browsers (as it would just open it in a new tab by default instead) so its up to the user i think.

**Comment by jochmann** [comment]
I think we have narrowed down the bug and found the workarounds and setups where the user can avoid this from happening. The workarounds are trivial and don't limit functionality. Trying to fix the remaining cases seems to be too much effort for little gain. 

Fix: Update Documentation

**Comment by jochmann** [comment]
Could be more prominent, but it's documented. Hopefully tutorial videos can alleviate user confusion.
